name: Hard at Work
favicon: 'http://the-grid-user-content.s3-us-west-2.amazonaws.com/hardatwork.ico'
layout_spectrum: 0.10562446457333863
typography_spectrum: 0.49682135228067636
navigation:
  - url: 'https://twitter.com/search?q=%23hardatwork%20%40thegrid'
    name: Twitter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75936-18
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0e0c'
    - '#413122'
    - '#d8b98a'
    - '#685836'
    - '#fffff2'
  brandStrength: 0.2226167267654091
  lightness: 0.6798470122739673
  saturation: 0.5780277983285487
  rhythmicContrast: 0.8549653482623398
purpose: []
