name: Hard at Work
favicon: 'http://the-grid-user-content.s3-us-west-2.amazonaws.com/hardatwork.ico'
layout_spectrum: 0.4861741561908275
typography_spectrum: 0.11404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75936-18
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090709'
    - '#feebd3'
    - '#be9c7d'
    - '#746356'
    - '#1b5a7d'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.75
navigation:
  - url: 'https://twitter.com/search?q=%23hardatwork%20%40thegrid'
    name: Twitter
purpose: []
